import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const LOCATION_TREE: { name: string; children: string[] }[] = [
  {
    name: "Toshkent shahri",
    children: [
      "Uchtepa tumani",
      "Sobir Rahimov tumani",
      "Mirzo Ulug'bek tumani",
      "Yakkasaroy tumani",
      "Shayxontohur tumani",
      "Chilonzor tumani",
      "Sirg'ali tumani",
      "Mirobod tumani",
      "Yunusobod tumani",
      "Bektemir tumani",
      "Olmazor tumani",
      "Yashnobod tumani",
      "Yangihayot tumani",
    ],
  },
  {
    name: "Toshkent viloyati",
    children: [
      "Yangiyo'l tumani",
      "Zangiota tumani",
      "Piskent tumani",
      "Parkent tumani",
      "O'rtachirchiq tumani",
      "Oqqo'rg'on tumani",
      "Quyichirchiq tumani",
      "Qibray tumani",
      "Toshkent tumani",
      "Ohangaron tumani",
      "Bekobod tumani",
      "Bo'stonliq tumani",
      "Bo'ka tumani",
      "Yuqorichirchiq tumani",
      "Chinoz tumani",
      "Angren shahri",
      "Bekobod shahri",
      "Olmalik shahri",
      "Ohangaron shahri",
      "Chirchiq shahri",
      "Yangiyo'l shahri",
      "Nurafshon shahri",
    ],
  },
  {
    name: "Sirdaryo viloyati",
    children: [
      "Sayxunobod tumani",
      "Guliston tumani",
      "Boyovut tumani",
      "Mehnatobod tumani",
      "Xovos tumani",
      "Mirzaobod tumani",
      "Oqoltin tumani",
      "Sirdaryo tumani",
      "Sardoba tumani",
      "Guliston shahri",
      "Sirdaryo shahri",
      "Shirin shahri",
      "Yangiyer shahri",
      "Baxt shahri",
    ],
  },
  {
    name: "Jizzax viloyati",
    children: [
      "Zarbdor tumani",
      "Do'stlik tumani",
      "Forish tumani",
      "Jizzax tumani",
      "G'allaorol tumani",
      "Baxmal tumani",
      "Paxtakor tumani",
      "Zafarobod tumani",
      "Arnasoy tumani",
      "Zomin tumani",
      "Mirzacho'l tumani",
      "Yangiobod tumani",
      "Sharof Rashidov tumani",
      "Jizzax shahri",
    ],
  },
  {
    name: "Samarqand viloyati",
    children: [
      "Narpay tumani",
      "Nurobod tumani",
      "Jomboy tumani",
      "Urgut tumani",
      "Paxtachi tumani",
      "Kattaqo'rg'on tumani",
      "Oqdaryo tumani",
      "Ishtixon tumani",
      "Pastdarg'om tumani",
      "Tayloq tumani",
      "Bulung'ur tumani",
      "Go'zalkent tumani",
      "Samarqand tumani",
      "Qo'shrabod tumani",
      "Payariq tumani",
      "Chelak tumani",
      "Bog'ishamol tumani",
      "Temiryo'l tumani",
      "Siyob tumani",
      "Samarqand shahri",
      "Oqtosh shahri",
      "Kattaqo'rg'on shahri",
      "Urgut shahri",
    ],
  },
  {
    name: "Farg'ona viloyati",
    children: [
      "Kirguli tumani",
      "Farg'ona tumani",
      "Quva tumani",
      "Toshloq tumani",
      "Oxunboboev tumani",
      "Yozyovon tumani",
      "Oltiariq tumani",
      "Bog'dod tumani",
      "Buvayda tumani",
      "Uchko'prik tumani",
      "Rishton tumani",
      "Dang'ara tumani",
      "Furqat tumani",
      "O'zbekiston tumani",
      "Beshariq tumani",
      "So'x tumani",
      "Qo'shtepa tumani",
      "Quvasoy shahri",
      "Quva shahri",
      "Qo'qon shahri",
      "Marg'ilon shahri",
      "Farg'ona shahri",
      "Kirguli shahri",
    ],
  },
  {
    name: "Namangan viloyati",
    children: [
      "Davlatobod tumani",
      "Mingbuloq tumani",
      "Namangan tumani",
      "Norin tumani",
      "Uychi tumani",
      "Uchqo'rg'on tumani",
      "Chortoq tumani",
      "Yangiqo'rg'on tumani",
      "Kosonsoy tumani",
      "Chust tumani",
      "Pop tumani",
      "To'raqo'rg'on tumani",
      "Namangan shahri",
      "Kosonsoy shahri",
      "Uchqo'rg'on shahri",
      "Chortoq shahri",
      "Chust shahri",
      "Xaqqulobod shahri",
    ],
  },
  {
    name: "Andijon viloyati",
    children: [
      "Andijon tumani",
      "Oltinko'l tumani",
      "Asaka tumani",
      "Baliqchi tumani",
      "Bo'z tumani",
      "Ulug'nor tumani",
      "Shaxrixon tumani",
      "Qo'rg'ontepa tumani",
      "Jalaquduq tumani",
      "Xo'jaobod tumani",
      "Marhamat tumani",
      "Izboskan tumani",
      "Buloqboshi tumani",
      "Paxtaobod tumani",
      "Bo'ston tumani",
      "Andijon shahri",
      "Asaka shahri",
      "Xonobod shahri",
      "Shahrixon shahri",
      "Qorasuv shahri",
    ],
  },
  {
    name: "Qashqadaryo viloyati",
    children: [
      "Chiroqchi tumani",
      "Koson tumani",
      "Shahrisabz tumani",
      "Dehqonobod tumani",
      "Qamashi tumani",
      "Yakkabog' tumani",
      "Baxoriston tumani",
      "G'uzor tumani",
      "Qarshi tumani",
      "Nishon tumani",
      "Kitob tumani",
      "Kasbi tumani",
      "Muborak tumani",
      "Mirishkor tumani",
      "Qarshi shahri",
      "Shahrisabz shahri",
    ],
  },
  {
    name: "Surxondaryo viloyati",
    children: [
      "Termiz tumani",
      "Boysun tumani",
      "Muzrabot tumani",
      "Sariosiyo tumani",
      "Sharg'un tumani",
      "Sho'rchi tumani",
      "Oltinsoy tumani",
      "Qumqo'rg'on tumani",
      "Jarqo'rg'on tumani",
      "Qiziriq tumani",
      "Angor tumani",
      "Sherobod tumani",
      "Uzun tumani",
      "Denov tumani",
      "Bandixon tumani",
      "Termiz shahri",
      "Denov shahri",
    ],
  },
  {
    name: "Buxoro viloyati",
    children: [
      "Romitan tumani",
      "Vobkent tumani",
      "Peshku tumani",
      "Olot tumani",
      "Jondor tumani",
      "Qorako'l tumani",
      "Shofirkon tumani",
      "Qorovulbozor tumani",
      "Buxoro tumani",
      "Kogon tumani",
      "G'ijduvon tumani",
      "F.Xo'jaev tumani",
      "To'qimachi tumani",
      "Buxoro shahri",
      "G'ijduvon shahri",
      "Kogon shahri",
      "Gazli shahri",
    ],
  },
  {
    name: "Navoiy viloyati",
    children: [
      "Uchquduq tumani",
      "Konimex tumani",
      "Tomdi tumani",
      "Navbahor tumani",
      "Navoiy tumani",
      "Nurota tumani",
      "Xatirchi tumani",
      "Qiziltepa tumani",
      "Karmana tumani",
      "Navoiy shahri",
      "Zarafshon shahri",
      "Uchquduq shahri",
    ],
  },
  {
    name: "Xorazm viloyati",
    children: [
      "Xazorasp tumani",
      "Yangiariq tumani",
      "Gurlan tumani",
      "Urganch tumani",
      "Shovot tumani",
      "Xonqa tumani",
      "Bog'ot tumani",
      "Yangibozor tumani",
      "Qo'shko'pir tumani",
      "Xiva tumani",
      "Tuproqqal'a tumani",
      "Urganch shahri",
      "Xiva shahri",
      "Pitnak shahri",
    ],
  },
  {
    name: "Qoraqalpog'iston Respublikasi",
    children: [
      "Nukus tumani",
      "Kungirot tumani",
      "Mo'ynoq tumani",
      "To'rtko'l tumani",
      "Ellikqal'a tumani",
      "Kegeyli tumani",
      "Amudaryo tumani",
      "Beruniy tumani",
      "Kanlikol tumani",
      "Chimboy tumani",
      "Shumanay tumani",
      "Taxtako'pir tumani",
      "Xojeli tumani",
      "Bozatau tumani",
      "Qorauzoq tumani",
      "Nukus shahri",
      "Beruniy shahri",
      "Kungirot shahri",
      "Takiyatosh shahri",
      "To'rtko'l shahri",
      "Xojeli shahri",
      "Chimboy shahri",
    ],
  },
];

async function main() {
  console.log("Clearing existing locations...");
  await prisma.location.deleteMany();

  console.log("Seeding location tree...");
  let totalDistricts = 0;

  for (const region of LOCATION_TREE) {
    const parent = await prisma.location.create({
      data: {
        name: region.name,
        children: {
          create: region.children.map((name) => ({ name })),
        },
      },
    });
    totalDistricts += region.children.length;
    console.log(`  ${parent.name} — ${region.children.length} ta tuman/shahar`);
  }

  console.log(`\nSeed completed: ${LOCATION_TREE.length} viloyat, ${totalDistricts} tuman/shahar.`);
}

main()
  .catch(console.error)
  .finally(() => pool.end());
